# -*- coding: utf-8 -*-
"""exercicio 2 lista

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBtmsNCk11pfh6QJtcct5TTqR4UR__qW
"""

import matplotlib.pyplot as plt
import numpy as np

# -----------------------------
# Parâmetros do processo
# -----------------------------
A = 0.3                # Área do tanque (m²)
Rv = 19.5              # Resistência da válvula (min/m²)
h0 = 0.2604            # Nível inicial do tanque (m)
qe0 = 0.015            # Vazão de entrada inicial (m³/min)

qemax = 0.040          # Vazão máxima (m³/min)
qemin = 0              # Vazão mínima (m³/min)

qe = qe0
h = h0

# -----------------------------
# Parâmetros da simulação
# -----------------------------
delta_t = 0.1          # Passo de tempo (min)
tempo_total = 500       # Tempo total (min)
n = int(tempo_total / delta_t)

# -----------------------------
# Parâmetros do controlador PI
# -----------------------------
setpoint = 0.35        # Nível desejado (m)
Kc = 0.00095          # Ganho proporcional
tau_I = 20             # Tempo integral (min)
erro = 0
erro1 = 0

# -----------------------------
# Função do modelo do tanque
# -----------------------------
def tanque(h, qe):
    q = h / Rv
    dh_dt = (qe - q) / A
    return dh_dt

# -----------------------------
# Função do controlador PI
# -----------------------------
def controlePI(CV, MV, setpoint):
    global erro, erro1
    erro = setpoint - CV
    erro1 += erro * delta_t
    return MV + Kc * (erro + erro1 / tau_I)

# -----------------------------
# Inicializações com NumPy
# -----------------------------
tempos = np.linspace(0, tempo_total, n)
niveis = np.zeros(n)
entradas = np.zeros(n)

# Condições iniciais
h = h0
MV = qe0

# -----------------------------
# Simulação
# -----------------------------
for i in range(n):
    niveis[i] = h
    entradas[i] = MV

    dh_dt = tanque(h, MV)
    h += dh_dt * delta_t

    #mudanca de setpoint
    if tempos[i] >= 150:
        setpoint = 0.38  # Novo setpoint

    # Segunda mudança de setpoint após 4 minutos
    if tempos[i] >= 250:
        setpoint = 0.32  # Novo setpoint

    MV = controlePI(h, MV, setpoint)
    MV = np.clip(MV, qemin, qemax)  # Garante que está nos limites

plt.figure(figsize=(10, 6))
plt.plot(tempos, niveis)
plt.xlabel('Tempo (min)')
plt.ylabel('Nível (m)')
plt.title('Resposta do Nível do Tanque')
plt.grid(True)
plt.show()

"""Fui testando valores de kc para ver onde o sistema se acomodaria. Inicialmente, kc era 2. Como havia muitas oscilações, era indício de que o valor estava muito alto, entao reduzi para 0.00048. Foi necessário aumentar o tempo de simulacao para 300 min para poder vizualizar onde ocorreu a acomodação do sistema, que foi em 150 min. Entao, devo inserir no loop uma alteração para +3, ou seja, sp=38 quando t>=150

O proximo passo foi aumentar o tempor para 400 para melhor vizualizacao da acomodacao. Observa-se que o sistema estava com respostas muito lentas, o tempo de acomodacao para o segundo setpoint foi em 300 min, e o primeiro nem ficou estável por conta de oscilações. Entao aumentei o valor de kc para 0.00048, e podemos observar que o sistema atingiu a estabilidade em ambos os setpoints. no primeiro, o sistema se acomodou em aproximadamente 100s, e no segundo, o tempo de resposta foi reduzido, e o sistema se acomodou em 250s

agora, em 250s, devo realizar uma outra alteração de setpoint para -6, ou seja, setpoint = 32. Houveram algumas ocilacoes, o tempo de acomodacao para o primeiro setpoint foi entre 150s, para o segundo o sistema praticamente nao se estabilizou, e no terceiro, se acomodou em 360s mais ou menos. como houveram oscilacoes antes do sistema se estabilizar, foi um sinal de que o kc estava baixo, entao aumentei para Kc = 0.00095 nota-se uma melhoria no tempo de resposta, para vizualizar, reduzi o tempo que aumentei novamente para 700 para 500s

Nota-se que no terceiro setpoint nao houveram mudanças na velocidade de resposta, se manteve em 360s. No segundo setpoint, a resposta diminuiu para 220s, enquanto que no primeiro, a mesma também foi reduzida para 150s

Outro ponto importante a ser citado, é que houveram sobressinais. no primeiro e no terceiro setpoint, temos dois sobressinais positivos, e dois negativos. Já no segundo setpoint nota-se que há dois sobressinais positivos e um negativo.
"""